[package]
name = "rustis"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.12"  # Die Version kann je nach Verfügbarkeit variieren
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"